version: '3.8'

services:
    postgres:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_DB: exerciselog
            POSTGRES_USER: exerciselog_user
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    exerciselog-app:
        image: exerciselog-app
        build: .
        ports:
            - "8080:8080"
        env_file:
            - .env

volumes:
    postgres-data: